
local builtin = require('telescope.builtin')

local function get_git_root()
    local dot_git_path = vim.fn.finddir('.git', '.;')
    return vim.fn.fnamemodify(dot_git_path, ':h')
end

vim.keymap.set('n', '<leader>ff', function()
  builtin.find_files({ cwd = get_git_root() })
end, {})
vim.keymap.set('n', '<leader>gf', function()
  builtin.live_grep({ cwd = vim.fn.getcwd() })
end, {})
vim.keymap.set('n', '<leader>fg', function()
  builtin.live_grep({ cwd = get_git_root() })
end, {})
vim.keymap.set('n', '<leader>fs', function()
  builtin.search_history({ cwd = get_git_root() })
end, {})
vim.keymap.set('n', '<leader>fb', function()
  builtin.buffers({ cwd = get_git_root() })
end, {})
vim.keymap.set('n', '<leader>fh', function()
  builtin.help_tags({ cwd = get_git_root() })
end, {})
vim.keymap.set('n', '<leader>tr', function()
  builtin.treesitter({ cwd = get_git_root() })
end, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
